### ISSUE TITLE
Please add a more detailed top level readme

### ISSUE THREAD

**Issue by truedat101** [changloong/libuv#6]
Most of the deimos style libraries for Dlang include some details on getting started:
- uses
- limitations
- D style wrappers
- maybe an example

Happy to propose something in the form of a pull request.

**Comment by patrickkh7788** [comment]
this lib is a simple c translate,  I use it with DMD betterC without any wrappers(because I can not made D with GC and class for high performance network app).

the code I write is like simple C example from libuv.   

Maybe late I will bring some D wrappers without the system default druntime. (I guess most people will not use it in this way).

You are welcome to bring your own D wrappers.

I am glad to accept any PR if they are suit for betterC(without druntime) use case.
